-- liquibase formatted sql

-- changeset thinhnguyen:1725203277954-1
CREATE TABLE tbl_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP(6) WITHOUT TIME ZONE, is_deleted BOOLEAN, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP(6) WITHOUT TIME ZONE, version INTEGER, name VARCHAR(100), price INTEGER, CONSTRAINT "tbl_itemPK" PRIMARY KEY (id));

-- changeset thinhnguyen:1725203277954-2
CREATE TABLE tbl_line_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP(6) WITHOUT TIME ZONE, is_deleted BOOLEAN, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP(6) WITHOUT TIME ZONE, version INTEGER, amount INTEGER, quantity INTEGER, item_id BIGINT, order_id BIGINT NOT NULL, CONSTRAINT "tbl_line_itemPK" PRIMARY KEY (id));

-- changeset thinhnguyen:1725203277954-3
CREATE TABLE tbl_location (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP(6) WITHOUT TIME ZONE, is_deleted BOOLEAN, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP(6) WITHOUT TIME ZONE, version INTEGER, name VARCHAR(255), CONSTRAINT "tbl_locationPK" PRIMARY KEY (id));

-- changeset thinhnguyen:1725203277954-4
CREATE TABLE tbl_location_shop (location_id BIGINT NOT NULL, shop_id BIGINT NOT NULL);

-- changeset thinhnguyen:1725203277954-5
CREATE TABLE tbl_order (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP(6) WITHOUT TIME ZONE, is_deleted BOOLEAN, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP(6) WITHOUT TIME ZONE, version INTEGER, total_amount BIGINT, CONSTRAINT "tbl_orderPK" PRIMARY KEY (id));

-- changeset thinhnguyen:1725203277954-6
CREATE TABLE tbl_shop (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP(6) WITHOUT TIME ZONE, is_deleted BOOLEAN, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP(6) WITHOUT TIME ZONE, version INTEGER, address VARCHAR(255), name VARCHAR(100), CONSTRAINT "tbl_shopPK" PRIMARY KEY (id));

-- changeset thinhnguyen:1725203277954-7
CREATE TABLE tbl_shop_item (shop_id BIGINT NOT NULL, item_id BIGINT NOT NULL);

-- changeset thinhnguyen:1725203277954-8
ALTER TABLE tbl_line_item ADD CONSTRAINT UC_TBL_LINE_ITEMITEM_ID_COL UNIQUE (item_id);

-- changeset thinhnguyen:1725203277954-9
ALTER TABLE tbl_location_shop ADD CONSTRAINT "FK1llv9ujvcc5o3r2javffhgqof" FOREIGN KEY (shop_id) REFERENCES tbl_shop (id);

-- changeset thinhnguyen:1725203277954-10
ALTER TABLE tbl_location_shop ADD CONSTRAINT "FK439smuw2817x7k7a1yqono770" FOREIGN KEY (location_id) REFERENCES tbl_location (id);

-- changeset thinhnguyen:1725203277954-11
ALTER TABLE tbl_line_item ADD CONSTRAINT "FK7c7vwyywuxakyfpqa7d6d2aar" FOREIGN KEY (item_id) REFERENCES tbl_item (id);

-- changeset thinhnguyen:1725203277954-12
ALTER TABLE tbl_shop_item ADD CONSTRAINT "FKd576ob0rkmn72n93v5n15ankv" FOREIGN KEY (item_id) REFERENCES tbl_item (id);

-- changeset thinhnguyen:1725203277954-13
ALTER TABLE tbl_line_item ADD CONSTRAINT "FKdyyguh9rt945x3suwx6lrmwit" FOREIGN KEY (order_id) REFERENCES tbl_order (id);

-- changeset thinhnguyen:1725203277954-14
ALTER TABLE tbl_shop_item ADD CONSTRAINT "FKmt4ofx5wvlq5mirhjkmpg4y5i" FOREIGN KEY (shop_id) REFERENCES tbl_shop (id);

